<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--<TargetFrameworks>net10.0;net10.0-android;net10.0-ios;net10.0-windows10.0.19041.0</TargetFrameworks>-->
    <TargetFrameworks>net10.0;net10.0-ios</TargetFrameworks>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>

    <PackageId>Nivaes.Typst</PackageId>
    <Title>Nivaes Typst</Title>
    <AssemblyName>Nivaes.Typst</AssemblyName>
    <RootNamespace>Nivaes.Typst</RootNamespace>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <Product>Extensions</Product>
    <Description>Wrapper multiplataforma para Rush.</Description>
    <PackageTags>Nivaes;wrapper; Typst</PackageTags>

  </PropertyGroup>

  <Import Project="../typst_ffi.targets" />

  <PropertyGroup>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeReferencedProjectInPackage</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <Target Name="IncludeReferencedProjectInPackage" Condition="'$(IncludeBuildOutput)' != 'false'">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)/Native/typst_ffi.*" PackagePath="Native/$(TargetFramework)" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
    <Content Include="runtimes\win-x64\native\rush.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <AndroidNativeLibrary Include="runtimes\android-arm64\native\librush.so" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
    <NativeReference Include="runtimes\ios-arm64\native\librush.a" Kind="Static" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Wasmtime" />
    <Content Include="runtimes\browser-wasm\native\rush.wasm" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="..\Nivaes.Typst.UnitTest\Nivaes.Typst.UnitTest.csproj" />
  </ItemGroup>

</Project>
