[package]
name = "typst-ffi"
version = "0.0.0"
edition = "2021"
license = "MIT"

[lib]
#crate-type = ["cdylib","staticlib"]
crate-type = ["cdylib"]

[dependencies]
typst = "0.11.0"
typst-ide = "0.11.0"
typst-pdf = "0.11.0"
comemo = "0.4"
libc = "*"