name: CI

on:
  push:
    branches-ignore:
    - 'release/v**'
    paths-ignore:
    - '**/*.md'
    - '**/*.sln'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - '**/*.md'
    - '**/*.sln'

jobs:

  build:
    name: ci ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
          cross: true
        - target: aarch64-unknown-linux-musl
          os: ubuntu-latest
          cross: true
        - target: armv7-unknown-linux-musleabi
          os: ubuntu-latest
          cross: true
        - target: x86_64-apple-darwin
          os: macos-latest
          cross: false
        - target: aarch64-apple-darwin
          os: macos-latest
          cross: false
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          cross: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.77.0
      with:
        target: ${{ matrix.target }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
         global-json-file: ./global.json

    - name: Run Cross
      if: ${{ matrix.cross }}
      working-directory: ./typst_ffi
      run: |
        cargo install cross --git https://github.com/cross-rs/cross.git
        cross build -p typst-cli --release --target ${{ matrix.target }} --features self-update,vendor-openssl

    - name: Run Cargo
      if: ${{ !matrix.cross }}
      working-directory: ./typst_ffi
      run: cargo build -p typst-cli --release --target ${{ matrix.target }} --features self-update

    - name: Restore Dependencies
      run: |
          dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --no-restore --collect:"XPlat Code Coverage"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

