name: CI

on:
  push:
    branches-ignore:
    - 'release/v**'
    paths-ignore:
    - '**/*.md'
    - '**/*.sln'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - '**/*.md'
    - '**/*.sln'

jobs:

  build:
    name: ci ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-musl
          os: ubuntu-22.04
        - target: aarch64-unknown-linux-musl
          os: ubuntu-22.04
        - target: armv7-unknown-linux-musleabi
          os: ubuntu-latest
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: aarch64-apple-darwin
          os: macos-latest
        - target: x86_64-pc-windows-msvc
          os: windows-2022

    runs-on: ${{ matrix.os }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
         global-json-file: ./global.json

    - name: Restore Dependencies
      run: |
          dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --no-restore --collect:"XPlat Code Coverage"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

